@startuml
'https://plantuml.com/class-diagram

class CuentaBancaria{
    - nombreTitular: String
    - apellidoTitular :String
    - numeroCuenta: String
    - saldo: Double
    - tipoCuenta: TipoCuenta
    + consultarSaldo()
    + retirarValor(double)
    + consignarValor(double)
    + compararCuentas(CuentaBancaria)
    + enviarDinero(CuentaBancaria, double)
}
enum TipoCuenta {
AHORROS, CORRIENTE
}

CuentaBancaria -- TipoCuenta





@enduml